# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temperature.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\"*\n\x15GetTemperatureRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\";\n\x16GetTemperatureResponse\x12!\n\x0btemperature\x18\x02 \x01(\x0b\x32\x0c.Temperature\"B\n\x0bTemperature\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t2Y\n\x12TemperatureService\x12\x43\n\x0eGetTemperature\x12\x16.GetTemperatureRequest\x1a\x17.GetTemperatureResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTEMPERATUREREQUEST']._serialized_start=21
  _globals['_GETTEMPERATUREREQUEST']._serialized_end=63
  _globals['_GETTEMPERATURERESPONSE']._serialized_start=65
  _globals['_GETTEMPERATURERESPONSE']._serialized_end=124
  _globals['_TEMPERATURE']._serialized_start=126
  _globals['_TEMPERATURE']._serialized_end=192
  _globals['_TEMPERATURESERVICE']._serialized_start=194
  _globals['_TEMPERATURESERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
